### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lucasbertolossi** [tomliangg/F28379D_LCD1602#1]
Hello Mr. Liang,
I saw that you allow using your software in the readme file. Thank you. Can I do a pull request to add a open code license (MIT)?

I was reading the website below and decided to ask you regarding this.
https://choosealicense.com/no-permission/

**Comment by tomliangg** [comment]
> Hello Mr. Liang, I saw that you allow using your software in the readme file. Thank you. Can I do a pull request to add a open code license (MIT)?
> 
> I was reading the website below and decided to ask you regarding this. https://choosealicense.com/no-permission/

Absolutely. My apologies on the late reply. I somehow missed the notifications.
